#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/03 06:05:21
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Amon.psl.gn.v20191129|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Amon.uas.gn.v20191129|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Amon.vas.gn.v20191129|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Omon.mlotst.gn.v20191129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Omon.sos.gn.v20191129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Omon.thetao.gn.v20191129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Omon.uo.gn.v20191129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.Omon.vo.gn.v20191129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r2i1p1f1.day.uas.gn.v20191129|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'SHA256' 'dee208acf21b705a85d91627d81577f8031c751b4d488da27a4f12f3fb8202aa'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'SHA256' 'ceb24d19f5993453bf6636a839af338612d56bb12d1c51afe012b41c980e19df'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'SHA256' '13039ed795267a20d2826520a0d864366b7f66a14b62ca2f62542f3a618fc045'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'SHA256' 'cc7433b8523efc52b71beed1f6fb53d3e1b4c63abc6950a6a2310b5cd414910b'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'SHA256' '1be0dffb2b1b4e4f5b8082a33b75ff094c22929500ef129368e32deed8b7d5fc'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'SHA256' '4f3714c56ed055121e6ddee9cd389ebeece043c4f2a86a31d13235d46010e7ea'
'uas_day_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_20150101-20641231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/day/uas/gn/v20191129/uas_day_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_20150101-20641231.nc' 'SHA256' '54b0d036456283d473eb289ae518a506850967372e00bb17a28eddbe743ed12c'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'SHA256' '436596d9edc2aaa88b4688c9c997f0beb8a75fc7a940c304ca363dd30ceef274'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'SHA256' '697eaff0ba344f57f5b85c2c84ec35cce0e06f1957cddb4fbe1ec1f9b6e4630c'
'vas_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Amon/vas/gn/v20191129/vas_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' '3ccf36d4380ccd0190281c0ebf6d27c4cd12fb3497a9dddebde7d2cf1fa93ae5'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_203501-204412.nc' 'SHA256' 'f7f9ec9c4b886818ddd0b57d9eb8ad7570f5b7d6fc0c1388b076bea0d3cc8eb0'
'sos_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/sos/gn/v20191129/sos_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' '917663d142bd1c150adc62c496d3ade63777241810afc8ac9c8f0bd87d3bb5fc'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'SHA256' '50cdce7105fddc6128bb00e0ed1be4363d290fdc5f2a993cb03fbe2dd7930027'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'SHA256' '6eac894660ce4c2a821a05b3da2d3848d45ffb446132aac15dc393021cce9e5b'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_208501-209412.nc' 'SHA256' '4a13b4e155d71d94e113d42192f5d64de392f3d7ded2279d59aefd2df80d2a8b'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'SHA256' 'fb6ad2dd5af949ae78627405f72174ea4ef574e07bf3ec291b38cdd841ecd136'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'SHA256' 'd64e7798fd6c74eaf27b977df82974d606379ffa0f6e6368c27042c6a59c8974'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'SHA256' '834f1a3a1f9d68d4276d51a6e8ac56553cb54b6c411076739a40f1c905fe2a0f'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_206501-207412.nc' 'SHA256' '346fa222da81906b39a9df4245a92a09de342097dd0f113c065e9bb843ddf8b7'
'psl_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Amon/psl/gn/v20191129/psl_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'b3eba94eb6d704f9923d63014bf145737cfa02debadb1d6eb7037e6ffd30c425'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'SHA256' '6dd2384219435a7cf08dfa8150dbb369b5931397aebeab781767097403d17dad'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'SHA256' '0de63cd967e36979185b0e6a01e8a687731ab478924a0670a5f4fe2eba5ad4d2'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_204501-205412.nc' 'SHA256' '675ef74b7bee579591cab7cd5b2dc1c5151b99b569c73249e458d85c3ef9725a'
'uas_day_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_20650101-21001231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/day/uas/gn/v20191129/uas_day_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_20650101-21001231.nc' 'SHA256' '1d328a9989ba31432fbb2d54301ce60c76600132107ce044980d425f484d18af'
'mlotst_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/mlotst/gn/v20191129/mlotst_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'ebf7970cea07c0c26e18100a1aa757b51de56f87a296bb000c246797246f6db7'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'SHA256' 'fc24a184d92d3c990e8b6dc9a57cc50cba7a5883c4f8c09f2bee73edbf6a1472'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'SHA256' '039d5876d4829568f33a5953e3131b4c2582bf9705985ddbca51abbc3afa0e7d'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_205501-206412.nc' 'SHA256' '8f8223149ffd4130fd992a6761019b1d7af5596bd675fc8aaf942d17e8b2ba78'
'uas_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Amon/uas/gn/v20191129/uas_Amon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'd51383a9f7db1781684092ae37f58f37f4b1f47d8cc3053672fba849b7544022'
'vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/vo/gn/v20191129/vo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_207501-208412.nc' 'SHA256' 'ba9604f2be40cf98ca50952069eabee84a78703319d1b573ea72da5fe1f89a71'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_201501-202412.nc' 'SHA256' 'ae33ebfc2a29112c42de25813a18cbacadb2cb24475134bf1e4654e83c31f213'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/thetao/gn/v20191129/thetao_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'SHA256' '2acabcf887876a367f938f3f08c69687da17d66e7d36aa6ba2871fbb3f5a3294'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_202501-203412.nc' 'SHA256' 'dd1bee101a825ea409a3b86176f0da26937457e541a5d66fc4e8f9ee168a0c6f'
'uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r2i1p1f1/Omon/uo/gn/v20191129/uo_Omon_ACCESS-ESM1-5_ssp370_r2i1p1f1_gn_209501-210012.nc' 'SHA256' '43cade24ef5fcb4b9b3222afa933e1c8b7567b7bad5ad4cb2bfee415ae25012a'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 34 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
