#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/27 04:58:20
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Omon.thetao.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Amon.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Amon.psl.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Amon.vas.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Omon.mlotst.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Omon.sos.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Omon.uo.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CCCma.CanESM5.historical.r1i1p1f1.Omon.vo.gn.v20190429|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'SHA256' '29e13369d1e37d92477359b47ae07503879135b7263878a20fab3486310ccb2e'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'SHA256' '195224fdf1a3727518239df2114b39fa5bdada9f2b70a94d8010cca00f6aa180'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'SHA256' '571cf396e722176634b57dd19cead8facbfd1dcdde1685bde421dd552b2aecc0'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'SHA256' 'b9a859a8c4f85837a93d169214f969c45e21dc4fd63d984a3cf2273b1b0b1319'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'SHA256' 'eebbf21a256451a015e0f9d054f147eb2e75d821745d1b8f505b3d063306c58b'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'SHA256' '00f2b0ff003a6f1029d93649b9964a8fb619c64ac56494ffcc6fa6930cd79dd3'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'SHA256' '75def707fb956c99083fb0b1a7d73599bda1149d34eb26f04c28ef53ef1540af'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'SHA256' 'c0ae8224c1459fe16c4fce8f75958ea3907c2aebb55107333ef6629c4e8cc5f2'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'SHA256' '8086b9fffa227f01f73d78434e59131fdee6e54b281e4b95e7d200af16ed044b'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'SHA256' '44676952688eb7832c2cc612aaf5e903e816733bcdcd2daaf452cf34a68e072d'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'SHA256' '1bfdbaba4a7c953df5d25510531b8b8f2a87437bee2b542919536bc93b2debe4'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'SHA256' '07857fb832717b9f044e9d75e8397523b7b65bbca186b76cd220944a828ad9d2'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'SHA256' '326320ae8d15bd66072401a0ca461cfd9a268fa0c5c0b9457afaf275e4008f0f'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'SHA256' '1a3b68093f123acc377e1d8969bee0efc8ad309b5e038ec5f18286f97ed8ba45'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_201101-201412.nc' 'SHA256' '05cf421314438459163c99c4eb3c4ea7a2c0d7a7df452c3ccce37111abe48681'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'SHA256' '789a7bf717d8dac818a99e028188d8432f52e85a10652162c19d7a68741bf265'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'SHA256' 'cc1e7fc5791ecd498e1e4e0c2ec44e49cce8d18734e49a3bc06642435458d251'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'SHA256' '736a3dccd62d2dff9c56193713eaa8845cd8e8abde4329dffb63628754afdd7b'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'SHA256' '346a0281535ead1ad3fbaa7ea574cd675677c519a0802360895ce484ae73bfc1'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'SHA256' '1785bd96b12305190c2c0fcc42ac4052d07969ad31f9c5fa19bdeb1c513a7a6f'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'SHA256' 'ab16eea35a58cd8d373f078ffedaf91aa240ea61118b5f71045f95fb34fee12d'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'SHA256' '841a1a5249cc415debbf6634a953822eebf026dc90cc4bc0ee105cc2b3949f97'
'vas_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/vas/gn/v20190429/vas_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '9e0db7824e92fc77f7bfc6f43b8402cfd74955a666ba1412dd5849e8efcf8c61'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'SHA256' 'b6cde66fe1cd4c6985659312bf47b94351978ee75a694de869d7e77b8afaf6ab'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'SHA256' '9e986555b461ab5df89d9fa3b69de3bb4f19db1397af2702912279e92d252aa7'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'SHA256' 'e1912ee46934937b3b843613c72939b426981a6434ed3ca68517047e86584471'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_197101-198012.nc' 'SHA256' 'b8489c082ff5ec098b759c874b2fb9c5dd058662c82e5c5f1799dd52705b938f'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'SHA256' 'd73d0b20c53206043a04d23659af5a3f5fee64a2f550f27bcf566db928bb91d9'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'SHA256' 'daf9ea1a570940dc1e17b0e3fb1cd4f67b505e6de731d89abe25786bfec45b9a'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'SHA256' '38c6a32725ba005f900f6f5af9709a3a8a45a5d21542f1da60957cbdb7f648bc'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_192101-193012.nc' 'SHA256' '703fcd443e985e35dae21f1c007a3ae2d8623b146b9f866b8c1a696d0ebd4f61'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'SHA256' 'f2d88a02ec358b09aba62f5dc46afce529a879f0edef6c102c9ae8a361351fe8'
'psl_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/psl/gn/v20190429/psl_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'b03599185476bf0aea12ac2cfec4e335fbadf9b78344c0f1e9180378443652ee'
'sos_Omon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/sos/gn/v20190429/sos_Omon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '85d5b461fc2c529d68d2ddf9e457f33086e18ffeee956e69c94ee96cf1e2acb8'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'SHA256' 'f424feea78465b8f812fa46f2ceb321c181ff18da9891aff077181cf1f9cf9da'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_195101-196012.nc' 'SHA256' 'dbd87a1d7d3b10dd098074e94ae85aa6eaea865f9def01b8a900b42248a37b6c'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'SHA256' '25fe46afe89b789df18a0eed73a0e2bcda523d1c6ad48e3c1da23707e5294bd6'
'uas_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/uas/gn/v20190429/uas_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '6db77beeb4cbc01c1ae52c201df281579d1dd63e898d392757e26318d93ff0a2'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_187101-188012.nc' 'SHA256' 'f49081cf7ec01759c1ce2250a5b06111da92c98238ab2ca7a258487dd514876b'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_190101-191012.nc' 'SHA256' '5cb18733382af5427e487a7272f86860ad7845a9a05c5d2a39cff46950e20e89'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_185001-186012.nc' 'SHA256' '61dba3841b91f53e257b06515e8b3d9ebfea0a4e9082bc47adae9300c0d3adad'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_189101-190012.nc' 'SHA256' 'f313d219b1484c8136d206a5b73ec7caebe6108043bfac798caf249125c1bcff'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'SHA256' '59ce6e04a66f183866b861bbfc4524a8d0adb954fecda889fa4455e82cad28d9'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_186101-187012.nc' 'SHA256' '2ba7ba62e8365da49370f689ea2b0ebb50df5ca82968063e955448075c5c62a5'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'SHA256' '06148a2ed97ed7105f59aec9f7056ee6bd60536d0c9c9f23c126415e4117ce35'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_199101-200012.nc' 'SHA256' '408bfb57a4fdfd2c6bbd63679c5e0a1e7dfc4505dc0edb0755f0634401c1326f'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'SHA256' '461d7768fc7d747a734aed93f86aeea95bc9dd0da0981f0ebebdd3471a49aac2'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_191101-192012.nc' 'SHA256' '3c650e61b5423ae8aab8e5f1945fc2155b1c0c873c658bfacbd7662f0e232c61'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_200101-201012.nc' 'SHA256' '8e946dc1575a8aac7f43fc77a1ec880b43852e9143d3f297adc9096ca9d13bcd'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'SHA256' '34f023037a3f50264826c3d447058fa5fe56c46838b8c9b1c1f43b251939ba24'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_194101-195012.nc' 'SHA256' '1b16398ff7b3ff596e0cfceb26901720354627cc6ae8d4599b9e62508fc84664'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_196101-197012.nc' 'SHA256' 'fa13a457e987452e3155f43361a04d8a1ca33e204f7276da850533b6a3175606'
'mlotst_Omon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/mlotst/gn/v20190429/mlotst_Omon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'a898302cca27f64d9139688f1f77db2349b9598a63c4a64f478569f76cd43ae4'
'thetao_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_historical_r1i1p1f1_gn_198101-199012.nc' 'SHA256' 'bcfc94bc2f9a5c133206e8be460d98261c67b629bd1c48614ff3f0df90a9a7fa'
'uo_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_historical_r1i1p1f1_gn_193101-194012.nc' 'SHA256' '7461167c8bb9e3f2f95decba8ac95a94f737ebbc1a97419941b8461f2907fb7a'
'vo_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_historical_r1i1p1f1_gn_188101-189012.nc' 'SHA256' 'f9b11263d940919293cd6db22dfc2bb47c4ea0b449a6b3e6c61d44b70aa26cf6'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 56 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
