#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/27 05:06:27
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Amon.psl.gn.v20181212|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Amon.uas.gn.v20181212|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Amon.vas.gn.v20181212|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Omon.mlotst.gn.v20210129|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Omon.sos.gn.v20181212|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Omon.thetao.gn.v20190311|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Omon.uo.gn.v20190311|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.MIROC.MIROC6.historical.r1i1p1f1.Omon.vo.gn.v20190311|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'uas_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/uas/gn/v20181212/uas_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'SHA256' '02bdb40845114477ee778afa0907a730dabb22861bea8c5d220884356a71a2ea'
'mlotst_Omon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/mlotst/gn/v20210129/mlotst_Omon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'SHA256' 'ebb081af15d846f574740e846b9ca8ccd5ae42fc41ca7f816680d14c7dcd221f'
'mlotst_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/mlotst/gn/v20210129/mlotst_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'SHA256' 'f14361369cae6a696b74d66063a1c1155d2d13b24f6762837bf0e64c62834135'
'sos_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/sos/gn/v20181212/sos_Omon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'SHA256' '5aad18d12c0f2414860883e355f36fe0e77d02a5b430164bdcbba6ac75dd55dd'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' '87a836a3999fd17648174f269cca1fd9e24c32c2ea1f2111afac86b4d5d5bf5e'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' '1f411ceec4e521cb8f0d61fa40db2bcb898c9a8e61be3678c41c2b4ff99f96c7'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' 'b9ddee719e721364ef523cb5d677f6aff7c63399b0366dc026367f1a25d052c3'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' 'cb78bd342a242541cf968290dfb556631f3a81fb50a4d417d54ac50ede101d96'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' 'fd8c65b1f63f389d38ce047b262c4b4f34994e28c7b276fb229d73e344ed0941'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' '655b3bf6de101abbeb9d660bdfce40f874117add9be1c14c7b1714ede6432371'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' 'c5537f37f9516cdb5dba977579b898d71db0d045deb17ddfc11c2f0543b6dff4'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'b290102d675cc504bccbac8cc41eb944653e43574ae854d19a9661cba7fe6a20'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' '7caf2a8c0dc68020ba332c7cd801c5d02738de90dd2b59325a9baeb76548bbdb'
'vas_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/vas/gn/v20181212/vas_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'SHA256' 'ae4f39dba4bf8fcc54ae5a774265c2ea43357c4bc14a94d9e049af3c8ded7122'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' 'f201504b59a772e99001bdad8fecec51aba6dafbb78e6ec0de0ae089ab89b96a'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' '622d6c7f184f3d706a7bc197cdff89f67727085e7d14ac414ce1bc94b7099038'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' '1aa81a5756341975857091d2bbf8261706f3738ac0c796321a73da8aac8f7aa2'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' '0d16c49fb46af1d7dbd32ce5370e3aff7e9c458e414d010ac34a888441d09e81'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '236362663f74d744315af14b541bca00d19571a83e588d7b5b342c9807777139'
'sos_Omon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/sos/gn/v20181212/sos_Omon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'SHA256' '76045cd3baa09cbcbbdea9a4c382af7bf227d43890d5cb1ee4dc80963663c7cd'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' 'e36dd4a44623ded1247983fd6468ebf94ccb7ba39da673c5600feaf163131da9'
'psl_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/psl/gn/v20181212/psl_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'SHA256' '308c6ce7d365f4659f020bd1a4b3fa81a84a73c92855c8b7a9535c87433d1955'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' '1ff6067ab2c2d26c2044f0f69d486c6c012d513c2dfaa1168f8a26b4e941ccda'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' 'da3d28ee441dae4b91c98797866b8953b82cd77dd4904ac466cee95349d6d8c2'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' '91e4906852d4f56b82848e7de2b01355d20031054d4bff986c7ba31a7f26ba47'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' 'c838049eb44f17ce45e8e9b1c62dcf6e503971ec1533b9b6aaf1c4dbadc60588'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '8aabc14e79aa8d9b2191dc5aa5843123b15193192365593e7e1849e90e287ca7'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' 'ca1866f7ac36cdabb083536bd616748d759367219e74426bb66b9cb268ad732c'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' '482128be27604572ed43f097cefa21c4c52c5a428d7a422fb2457dda495f4ff8'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' '077a0b7994a3eec3af8f3aa3b74574fbd3feda19bb4388f4e5071f02d022dfa3'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' 'b07aacbce1957c7d9d5175a7f4d77665661392fae1dfe3701d294067ff4cd4cc'
'uas_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/uas/gn/v20181212/uas_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'SHA256' '6dd067d8860458e0ffe582ec428a3f9bb2460c21117b282a230d59f696926aed'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' '3bfe456445350956baba68bbfaa95be861862230a917ae60031f9a24e9a7906c'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' '63beb9856bd2f1d5a7062509620ac004f017c94a9e877b0b726c4e661a785e3e'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' 'e3836ad1a8b48f4217e254dd84b755f817794cde00b0e635d285dd7b9dcefee8'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'e3ce355841c8d02d69351affd33b8aad2a90a77297c0694e62ebe798835b8f2a'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' 'ef18f2935bf37e9fadc1f98cc0a85e27abee146ee2fb89665870856675b8b8ad'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '6966d129775b2ad65b7a1af47c629bc5ee7cc875f0a3f7b5d838eb68efd820ec'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' '2efcb5f8e2a1a12f815182db39937f6726c39af8b349ec3c3bcce4a3ef3488bf'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' '7270c64ad24cb9c534ca878e3becfaabb5404fd3a7d01d27c74d07430f8f240f'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' 'eed348dfc62b8aba27e035466703e0d0ae4558ec603becead008f03492ed462f'
'psl_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/psl/gn/v20181212/psl_Amon_MIROC6_historical_r1i1p1f1_gn_195001-201412.nc' 'SHA256' '931d3831470318e3ca7a90224ea0e1dadbbb7aaecd7588eda75612f05c9fe084'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' 'e8e68ac937fcc315233668e2fd56462495364bd22eea75c4c7535320218ef9ac'
'vas_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/vas/gn/v20181212/vas_Amon_MIROC6_historical_r1i1p1f1_gn_185001-194912.nc' 'SHA256' '08f1b1dff850cf92bd46a0b7c11e60443613b9c03c84fe3771c44de0472ccd77'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' '6ee58479a76282b95d33e515bc57601e1ab716f3102b66be439daf1d869d11c8'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' '578415fc85ed1dece31b02f0ccdcec7f420e1dcdd358461314a75b842e09bc2a'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' '8150185824371faa5552f0cf3257f1c0eb64abf8748e8b264090a3a2cad73fb9'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '5c22d2e23b12702d607fcb770e5397da895858d1771e1ea4e8b30b4653bd90b0'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' '4418b00c9b90208b84961ba2af41bd6ec9211ba0fc9a2d2093f15b9ca724cc83'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' 'be18da5ed3d2bd9067126bc8c33fd2337b4711d740ef9b20ba4bcc5b4c7da51b'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' 'af6ee2f71baf12ae8172a8b855eef85635e48312abbc9cf3f4e76976dc8edcbf'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' 'dfdaa16a14a413e3cddfd2614bfef2866ed16fd1532c0f88b9e72e08962b0744'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' '132f6a37b3a36a7ab57c660f94677de786b8826f9f2addb31dafd5eac51ec87c'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' '1d0c12dec91a4f582602e1adcd0fa360122a9c3adbf0535eae368aa165b37eee'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' 'b005c85f501a8ac8f119e2f6f77a99f773bd7be8a3972c8b39f0053ad4a1762b'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' '856246a44be32f48d1dc80b85e267e722a7155b2970867e2d7ad66f308b60dfd'
'thetao_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/thetao/gn/v20190311/thetao_Omon_MIROC6_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' 'fad5621680a5fe10a9dfbe138493e7fe73565382a2db2693ba93a366ebbc9978'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' 'aae46052ad105f7be05dc03af7f10e24b5ecda049e459979a3524e4acd39feee'
'uo_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/uo/gn/v20190311/uo_Omon_MIROC6_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' '84802c69cfaf532ec706e13cd6e40e67d89872f9cb50930b328b9eccf4b8f7cb'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' '1aa9ea8f4648aebca4f3966082c052420261fc4eb72bb43d358ccb91891b122a'
'vo_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Omon/vo/gn/v20190311/vo_Omon_MIROC6_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' 'f9eea82386ac7dcd1524bbb2865c1442142d562ca7c41373767486a01b7d913f'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 61 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
