#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/27 05:01:10
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Amon.psl.gn.v20210114|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Amon.uas.gn.v20210114|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Amon.vas.gn.v20210114|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Omon.mlotst.gn.v20210114|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Omon.sos.gn.v20210114|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Omon.thetao.gn.v20210114|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Omon.uo.gn.v20210114|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CMCC.CMCC-ESM2.historical.r1i1p1f1.Omon.vo.gn.v20210114|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'mlotst_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/mlotst/gn/v20210114/mlotst_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '6c6db454cc702cddab3662087cf8dac62bceac6a755990bfe257c0b77cfbf331'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '47b745d5da9ada00d2855585514e216ecefbb76442f71345f2434f4f2bce9d6b'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' '602391cacccb6944b0f6b217728ee0b16e837c0cd2784274a4da8eeb738bad09'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' 'ee44d3577e4fde6c4e2b0987beda9d7b0135125bfce89dcd4568c67ec9e1fdb4'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' '0f3ed4ecbc1bd61b87ced12665508fb6acd8a19041a3d39acc431b35587aae48'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '6b3a4dbd8419ddedad089a413e8d5220c253376e89b2f0c5d02244200e032f98'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' '71ed4d20899d553848fc06eaaf354df092ef9ad585822e9ba5a710ba3eb8787b'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' '163d84198a08e5b516d73a74d02c9e6267873015eae581d84ab5ec5d6fdadc6b'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' '94f90b394a99f5aca124cc5d4216bcb6d80a79222eba91f040a20df506bc101e'
'vas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Amon/vas/gn/v20210114/vas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '5a14c4e1514f51ace7ea6a25525b90b0b57a6dd3e04b9c897aff21c177c6cb3a'
'sos_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/sos/gn/v20210114/sos_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '9cc3a11cd540069abce1a07584e133a02935dc86ca26843f2981cb96bd96a624'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' 'ef571fc02dac28b8bd6b8c9f9b53d58a1bf2c404225a0a5f00e711fe2f592a57'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '5ee1a208ebe724e1ebf94b8151d2b1d19ac51a76feedeb13169bd975b71bfd5a'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' '532ce0ff9754b32deb682f42a99cc037af839de969ecf37a100af7ec364680d9'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' '0cde42274e31cbc3a64d5e8bd6b8cf527c8b03e04de15bc7b12e61a0398c5be0'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'c1a35dda71f8fd56601c829bd659b1277acb58221762803041cdf2f31bf0a51f'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-186912.nc' 'SHA256' '24b0b80005b7f4c37db89ed6e057fbbbcdc37977fa2ee09f8c47e15144694ee0'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'd9d5bef9eecc79811390030bd8e0401301067a3c3df928c5c1b5f2e5071ee776'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' '67b7c8284c173dea5ca4c986c9c0469fbcd773a4db0d4ea5afa40a62a6570615'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' '9eb70de4e7f318271d4c21dce292c778f0116de9db68ae1004ff1977b7fd21e2'
'uas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Amon/uas/gn/v20210114/uas_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'f00659e44ddee9bd99d23e7746fb89719f71010434e3a048d99fca4d82e2d9bb'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_193001-194912.nc' 'SHA256' '62e1077881e312079087274f39dfef9c31ca2d5ef1384298ebee739e2df0435e'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' 'da4b7683b218c17ff24eb68bf26c16c9a72ceb8a8715586ae2a4ce3111e9ccc5'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' 'f4dcafc5147fe7b88a6db7fc0ead2296c7409d61e53da798228f53e84958ebe3'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_191001-192912.nc' 'SHA256' '484ff46aa3814991c70cdf160e36d2b3e78f3f85d6993ce3ee93d58c7ad3d51e'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_189001-190912.nc' 'SHA256' '6b5dbac57e8fc2532d590f630b47db43d55af6b8234ffb2d4dd81385ce7b091e'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' '8f7e0994336ff2c2b1082dafbe166bdf6dd926b95b58edfeb3b2ff55bf0f50a8'
'psl_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Amon/psl/gn/v20210114/psl_Amon_CMCC-ESM2_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'b9003670bbd0af80c300b255ec155811e2ac584648f902d2267e7b6c160d7323'
'uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/uo/gn/v20210114/uo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_195001-196912.nc' 'SHA256' '7ffed83dcdc93ce8d25b86686fad0ddbffed307b0bad25e00a23d329ab4c46b3'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_199001-200912.nc' 'SHA256' '34c063ad77e56ea97856016a2cd8c550c81ad3ebc0b127bf178e04c321cbc021'
'vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/vo/gn/v20210114/vo_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_187001-188912.nc' 'SHA256' 'bf47271d1c4f1d00b1e9f275e3da427f021644f35f1ee159885535454b8a2e03'
'thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CMCC/CMCC-ESM2/historical/r1i1p1f1/Omon/thetao/gn/v20210114/thetao_Omon_CMCC-ESM2_historical_r1i1p1f1_gn_197001-198912.nc' 'SHA256' 'ad28023cee20f498959a9b989348e3d7f1b439f7070985e594c2bed8fb41da79'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 32 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
