#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/03 06:55:36
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Amon.psl.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Amon.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Amon.vas.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.day.uas.gn.v20190429|crd-esgf-drc.ec.gc.ca&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Omon.mlotst.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Omon.sos.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Omon.thetao.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Omon.uo.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r3i1p1f1.Omon.vo.gn.v20190429|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'SHA256' '14148b6b80f364a2e2da45a3f47c17c7f246e3bc68b3efa5d8335c453fed5714'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'SHA256' '9f7d1fe1c260c5b090354e7e72bf0bceb770b28ab294b6f9e095f0f61b2b0bd2'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'SHA256' '306c2622971ea254c8b98733cdd62274bb2a78a189f082629407c7f3dd867838'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'SHA256' '3d9bd4ea463156407514c880539ae449031da14d47d9b4a17a82d324eedd34c7'
'vas_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Amon/vas/gn/v20190429/vas_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' 'd5f31482dbfe1061cce927d8d89af43bbf3d764775c176bc5fa9f8ac74355146'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'SHA256' '8422c37d12f453b1721b202a4d0ae914fd83a1908ff6f54642b3b8fcfc993f78'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'SHA256' '59ee7721f5f360d1e39d5d804ed8d924ad1e2c82602b4e255818d1d61452cfcb'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'SHA256' 'b14b2703670278c14d49ecfda87af9a21904732c69be853931e47bbb8a54ad71'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'SHA256' '8088ecb3254118cf181c1d5b3b24e26835fbffa4dbd096a7e8aacb65a7b051c0'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'SHA256' 'fd78686497d15980d0f427bb5b81dfb5cb8dcfde13332b656c77dc18bc031676'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'SHA256' 'b96ede6a817f4e89be9e8e9876b81e6f32805bf1f2d4666add104d35caf42e9d'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_208101-209012.nc' 'SHA256' 'e989c3285cd9ee912aa277811e5139ad8335185559c7cf017ed33cf41339bb46'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'SHA256' '71b359b439240bda1793f6d4d7ac142be7dd68451f5375ec94e3e4f76f2cb4ca'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'SHA256' '398a6dc9b940eb1a2015f5be3ca044455c0a35ffa500a86ad62eadd93337ac31'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'SHA256' '6bb03e600e3afd94f9cfcb215026a56491af90aac04b326896dc140163c48ad2'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'SHA256' '50b4ef2872f796213b139b6814c4b06ecbc391f28cd5d311fd6b3ddcc42f0dd7'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'SHA256' 'cfb16730c53de73ee2d6b74f4f0815cccd36171f4b5c0746a6e6b3d9a9ab3456'
'psl_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Amon/psl/gn/v20190429/psl_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' 'c8b2f3616b694d890ff42848bc779a94090a4afa8711a61c843f626b3469a007'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-202012.nc' 'SHA256' '4f5aa6078a425d8bc6de7aaaa03647ef68501693bc6ae4515fae9d5b19205518'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_202101-203012.nc' 'SHA256' '67d94f88567f4cb3ef12eb56bbb13b71b0df6e81ab11cab4b14e2673a991ffe5'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_206101-207012.nc' 'SHA256' 'd0ffa1e125d413a0bef1fcd460b86a4159c4957a9a4619839ba5ce15029f9e05'
'uas_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Amon/uas/gn/v20190429/uas_Amon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' 'a9942ca0d7cd8c72b0f3bf68d4d1f3ab1d113571eabc53952a1914889dfe99d9'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_205101-206012.nc' 'SHA256' 'bc6b88186586944843413f4e7508c0f48fb5e98c760560d4c9e8de91c11e8415'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'SHA256' '6c2e5292fc5105da6c72dd79abe82ac984e7956e4e56ef12b1f1bde82d7726b2'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'SHA256' '3edfa09ea8098e509d91479a85189bfd27b0eaa3501ed3ec5d13003dc5f2d404'
'thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'SHA256' '38f7e90fff9a6c44dc341b48e1c681389a2f639cea39bbe40e3dc868dfd03146'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_209101-210012.nc' 'SHA256' 'a11e3411f67a0a844f37a393341bf05a16e3254474dd5e8432304e8482e07124'
'mlotst_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/mlotst/gn/v20190429/mlotst_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' 'a6caa9faf8125912e897e4a3f32209085be85570dd257d69ae31965ec5b0d27f'
'uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r3i1p1f1_gn_204101-205012.nc' 'SHA256' '2a462a2135811b636d64d030948fb7896f291218e7fefd72f9872536fae50e6d'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_207101-208012.nc' 'SHA256' '893a86b1d82b27107d75190ab6ad2bdc47b82ece016cb3daa915884c1b3d591a'
'uas_day_CanESM5_ssp370_r3i1p1f1_gn_20150101-21001231.nc' 'http://crd-esgf-drc.ec.gc.ca/thredds/fileServer/esgD_dataroot/AR6/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/day/uas/gn/v20190429/uas_day_CanESM5_ssp370_r3i1p1f1_gn_20150101-21001231.nc' 'SHA256' 'e12ca01cd14b3923615783a66a0fc1b10e6bf01a5b54deb2b20b8dfe0dd88f6f'
'sos_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/sos/gn/v20190429/sos_Omon_CanESM5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' '97544c9bfb028104cb3279f2657629a35ae54efa92b22b6dc88e61527f456344'
'vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r3i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r3i1p1f1_gn_203101-204012.nc' 'SHA256' '44f3cb2ba92f39cf2bd5d3dff8e5e3bfe62c3250014bd5dae933d23e0cc0e7c3'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 33 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
