#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/02/27 01:17:51
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Amon.psl.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Amon.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Amon.vas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.day.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Omon.mlotst.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Omon.sos.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Omon.thetao.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Omon.uo.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r1i1p1f1.Omon.vo.gn.v20190429|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'sos_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/sos/gn/v20190429/sos_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '52eb19b13943a1ce88ca2029d1d8d81d751d729d9159d66d43922f044e671227'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'SHA256' '072c7bebee1ddf70209eb9bc35e5d0b0e56cb80f3f5ba70db5e11403dbaecbe4'
'vas_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Amon/vas/gn/v20190429/vas_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '111c2e56fc0dfbfad1f5d1fd2aab527eeb1e89c60eb0e2ab557da8c9bae6ed26'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'SHA256' '8ceb8477e979eeca02bba87b873224a2b200a939a1e89183ccd06d1eac4960da'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'SHA256' 'adc7cd5d35d79b1824b80eb16ed27c5b62f09246d7fc07ec601d66db96e40aea'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'SHA256' 'baf8872449333f36a7c283a4302066347d2960562642268844a2a45feb49d91d'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'SHA256' '1b2bbaf8a4463cebe4df5c4a6f1fbc2264601319291b8bd55e958a7954aa831f'
'mlotst_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/mlotst/gn/v20190429/mlotst_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' 'fafe10c0f66b9fc48920f0cb99ad96d7e379a3d652937a5626fd438711c12b87'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'SHA256' 'df532d8ebe4cd08754b4519ca994f3cc5b4afd5776a7bea28860274bc8d78994'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'SHA256' '7deaecf13de2e311afe9095538c35a1e2a49bfa03dc0e8796e3f66267c142347'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'SHA256' 'c15216291365dcff647d9fdfadee21b4d0517d3e28b82bcbe8c5d62fe6930155'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'SHA256' '6d4edf6a009c811c0cc3f3c9baab3d76ff4bfa822d61cd15b5f6bcec2c31f0f1'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_205101-206012.nc' 'SHA256' 'a143a774055ef08a64c2e4c55160f6252bb81b7535744cd4f250302031766641'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'SHA256' '4f335eb726d55da99e83843155ebcff98785cd8bd485864ab485464b7e5f6fe2'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'SHA256' '231ea707d421bdacd458749aef2aa7b313478a03ccde6995bc9bbf6486737c87'
'uas_day_CanESM5_ssp370_r1i1p1f1_gn_20150101-21001231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/day/uas/gn/v20190429/uas_day_CanESM5_ssp370_r1i1p1f1_gn_20150101-21001231.nc' 'SHA256' '8731bd91700bacdd599e2ee535b7a807af1c7ddaaa7dd71b47d4190d24a22bc8'
'psl_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Amon/psl/gn/v20190429/psl_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '4994d4ede0adaa0fe49e84d9782fba0f59b21478bdd98a77968345afb723befa'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'SHA256' 'cd836af780f359d27fc6540bd425d32fe1749494fabb79174bff683943cf8874'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'SHA256' '7069a37484ddcf4e2af89124f525f4e8400601e88198fe0fb9a2a71995e2870b'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'SHA256' '8b2bfa9187e9313718e41c9127992083919669446e5b83d4701a4bbdf647ccdf'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'SHA256' '00ef26c86fbba1541666b49c5db45252363daf5ddbe8427452352699275d99cb'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'SHA256' '5fdfb2ca4b859e80f355b2df5f1215ec1c51e4506d8df086ac6e0c61537a7ea5'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'SHA256' '85c8d546624a425671dd7f0b350624155c65a22c6f5129d84368b3202a7c497b'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'SHA256' '010ef9d2f81bbb7256de4ace275049d045283f5713b002c226c2f288be3a39c2'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_209101-210012.nc' 'SHA256' '3279931d72a19f7fbb713e78e00016a3679b6972745bca9801f5bd683a23a755'
'uas_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Amon/uas/gn/v20190429/uas_Amon_CanESM5_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '515029056ff0bb40b7002cfe6565efa8e5afa4fa774eceafa252ece21132284f'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_208101-209012.nc' 'SHA256' '9a065bdcd4e978c6d32591e3e973aff3c98a0b8bf50beb597da194b3e0ba3f50'
'thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r1i1p1f1_gn_203101-204012.nc' 'SHA256' '6f4d9bad9cea8b3dda3ed0df6189d705f4e38b2e1cd5d0678c359562683d7422'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_207101-208012.nc' 'SHA256' '6bc9dd9473136523a32d66e16d3a05f0e258cfca688cf13933d783a672646c71'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_202101-203012.nc' 'SHA256' 'cbfa3a4b9268cee2c068457ae6476743b97ada57ae6c0ff14e18c06975af7c06'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_204101-205012.nc' 'SHA256' 'aba80962433d7602a7e193ef9b41448325366e6a93f1640719958425a3404a4d'
'vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r1i1p1f1_gn_201501-202012.nc' 'SHA256' '56150e559be1ea9cfd04ad50a96eddce46f0347b3092e4f580a7f6829e4d206e'
'uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r1i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r1i1p1f1_gn_206101-207012.nc' 'SHA256' '4a21b0758857177cc4f82a6f2fec972f25a1ee1176700908fa71e38c60b823bc'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 33 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
