#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/27 04:55:22
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Amon.psl.gn.v20191115|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Amon.uas.gn.v20191115|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Amon.vas.gn.v20191115|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Omon.mlotst.gn.v20191115|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Omon.sos.gn.v20191115|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Omon.thetao.gn.v20191115|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Omon.uo.gn.v20191115|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Omon.vo.gn.v20191115|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'uas_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Amon/uas/gn/v20191115/uas_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '8469181121931274e64a291b20038a049d47ae80c4ede3e094274587890f58ae'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' '3e86c60cab41b3af0669306886495c74979b91e70a73323e0347d90398d56370'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' 'fad4df9d930cbd386e5a41c758f67adfc72a36e679c7ed40f2268863f257d388'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' '7a8da5b97fa9ff9486d5abe4f79e0ad14cc521e0319f9ae168b97832ec322d60'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' 'd6b24f7786d68a8e3f4a2b6186b180de1313aa09ce5d0c3b5315d8f2453a89e0'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '20ab6303126357441a6ae0af16db8cd091ca55f12881489bae9a94719d47af33'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' 'f51391f177a77be21b9b2ed5ce0001f0ccee3c0ccf52791943f6b95ac3441c4c'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' 'e5c306b21da5b31ea558ee8491adb9f7da84197c4af005df98146a1185bbb2dd'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' 'd042c86a86e210b9dc057f8d7786af5f2cc4a3cd179ae42308c1f0d718d5ae4b'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' 'e197596c7fd6f6d94b37ae0e40ca7ff00f35622ce05bfed07a4b2ef55231be01'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' 'e0722ae40a66c9c8c93b214184acef9f6b2198c5343895c18c5d2ccd53774b1b'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' '94705514cb52432bb4b6d114fa70cbb9a26b63d979d06051ce74ac25449efca3'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' '413141e2950a33b3f61070d8921c15e745d0ff9e4ba9badf772c9b0b4290f78c'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '9cba9c0658233a45ef4ebcd07842ba2cf8690799772e9ea8db9512e8d39a490e'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '15efa00349be2c66c7b0243baed81d473cf8df4007ed46ee87cc149ee975f878'
'psl_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Amon/psl/gn/v20191115/psl_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '962576384fe0e0b6ecef3d6430e8bc5e7dfd475fb81b2badc517b8ebba7310b3'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' '9a5deba4e2e18fb699b3dfc9a656f1d7cec7bee59f2983350016d83d5f274ebe'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' 'cc28c0ba2b3a319afc1e9029e578201ff4cbd6487be6f0749443af9f96d31074'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' 'ffac04493756837024b4f65f9b0e30178a3f551de34d3bd4ceddab28c8403f47'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' 'e2c9ce96d08353dd11dc9c109265200ebcf69639f1d6a77c7b16831c84ae5ee0'
'vas_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Amon/vas/gn/v20191115/vas_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'e02785ecaac84d1a63ef3b5eb4c4d494592d6f133234ac641623a9885563591a'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' '5656ad9a542b67f59e5695b06e2673a009951f69a58658220c8031c2f17fa013'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' '7fce151bb0cd208d8b3908782982b35fa8abccb13c409012578a7b164946479d'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' '8e4bd8f093490ca4e4a2e38f2dc0a61f2a9e9a39bf0244a5de1ab89317270c91'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' '526d905a1c3932fb181529862e93b3234a867171a6c1282af9d47150df54a889'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' '91f91f835f038090272be255ab89016ed449dce4a3933a556b534eabc3b262fd'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' '8c12f761f96be083402853fb241d00da5b78ec3c57ef60fac0b1e97648ce749a'
'sos_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/sos/gn/v20191115/sos_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' '175df20f3f034bf9e0f06aa13e53467bd184d38f269034e8138c6c1e0cdd4c6f'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' '2165a9c57cbd78c129accdd41a8fb2f053891216ffab1a55348daaf17738bd47'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' 'd3fbde0a693bf3f7091f337420f9813c278c74ffefcc177be932dd0a0e83969b'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' '43359817011dbd35a9bcfc89cd4d0fd85fbb6d0f0a366061f1de9e1f882a050b'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' 'cb0766720c980053f0cf9e158eabbe4feb771da1e74e192727430d5687e3bb5e'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' '85de6c48fe4b445d6fd0680d6b4f6e220a722c8c4e806f44034d9b78bada86c3'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_198001-198912.nc' 'SHA256' '12e40611b3fce5b4cbe7eede3bb633951bb96055b78e0a2a9c383efcafd87ebb'
'mlotst_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/mlotst/gn/v20191115/mlotst_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc' 'SHA256' 'c67a54afcb6fda4140b3345fb05b77620fd38492874b7fa8c3f957207f82ef68'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' 'de4372883c1351524e948c21c34f508db4e67cea8489083f636560972803def2'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' '73b50ab7e60b226cb4dae35e1e881590d006d4f55ed520c9daa414267cfcd1cc'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' 'a6d6b7a336116e4cb5de0852de394d73da749395d051f607f1eb32184e7f6bd0'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' '9cf6d13118819a0f8c3a4592fc22c2aeea1e3194519b619458bf40cf918e79a6'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_201001-201412.nc' 'SHA256' 'e244a76db5058f07a5a9c69d4e53b11c103801ce295c2372a79e490127c29bc1'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_186001-186912.nc' 'SHA256' '03ed23edcfb356156212b1983eef5ec2be7b8112758e197479acfba32ac1d030'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_191001-191912.nc' 'SHA256' 'e0e1024af1716478d291a95f56637ab835d5da5b53465331efc755a2705506ed'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_194001-194912.nc' 'SHA256' '74759c5d798e599d663eec883ce9e3e399bf2ed1a49f3d1fbecd62745ac8d053'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' '5b9449d71987bcbb7e3b8c5fe3ff41b881d6bad64c94da17985c710240dd410e'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_187001-187912.nc' 'SHA256' '3e4bc33d3d722c257527b4df961ba50be3c30e4c568f7b21549d0066aa48886c'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_189001-189912.nc' 'SHA256' 'cfafd8e5874ac326f012b96c1e64e4c14a7612c836c3f9367c5a391c876ad6a7'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_195001-195912.nc' 'SHA256' '065979022520cc025acd9bd99ef636f587037e049e3d7e64ec46b566010e4571'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_197001-197912.nc' 'SHA256' '190ab19ebc5837bb86338dec3210ca5dab765f559332df4e6a7e80ac0549870d'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_199001-199912.nc' 'SHA256' '6366fca136832a2417b6c305d1041ea6ddb553bfa7423076f425771555ba25f8'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_200001-200912.nc' 'SHA256' '37d419895d63594d0bfd3dc7c83bccad610c56a2715dc6abe7a013ced2522983'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-185912.nc' 'SHA256' 'a8deb13640d6b311a9ee1e6ae7505e32c5dcc9b13250db49d33d6052978b69d3'
'vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/vo/gn/v20191115/vo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_190001-190912.nc' 'SHA256' '02661fb1c2d5f8d868611902ca31add1439fcf893e5e7ad3d50980bab3e50107'
'thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/thetao/gn/v20191115/thetao_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_193001-193912.nc' 'SHA256' '4dfd79b47278e4bb86f9bb8853aa0226e7acd2bccf99622b3605c7569f637314'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_188001-188912.nc' 'SHA256' 'bd3c0c3b872fb01424bb398cccb67226a50eee3cf79328a4254c2327a32d6e49'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_192001-192912.nc' 'SHA256' '86b861d29acc1f0c98fd1bd47a58d95a0f970650a13259900ef100aa039c76c6'
'uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Omon/uo/gn/v20191115/uo_Omon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_196001-196912.nc' 'SHA256' '5416910d3df9c5fdb7448a82fc1c5b1e5d08874bc04b3a92b5ef88f3fecf81cd'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 56 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
