#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/02/27 01:18:27
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Amon.uas.gn.v20210202|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Amon.psl.gn.v20210202|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Amon.vas.gn.v20210202|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.day.uas.gn.v20210202|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Omon.mlotst.gn.v20210202|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Omon.sos.gn.v20210202|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Omon.uo.gn.v20210202|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Omon.thetao.gn.v20210202|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CMCC.CMCC-ESM2.ssp370.r1i1p1f1.Omon.vo.gn.v20210202|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/thetao/gn/v20210202/thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '687778751485166cf42624a14829c65b6632432f2e12c45f5b342443be2b8c01'
'thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/thetao/gn/v20210202/thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'fd68a028b52f7ef3bee01cc0920d59fac8b4fd41d6c5566e95f0145d146256e3'
'vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/vo/gn/v20210202/vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' 'ee36a3eaddd33370bd0d5b9eed7c02a3b731afc924a85faaada217ee15d7e38f'
'thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/thetao/gn/v20210202/thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '29f52860d5c03b7cb0adad05e7d9ce60aa8dc49cc038a657b73f03f2633a1220'
'vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/vo/gn/v20210202/vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '45a4da692d55d0f863a2c7c557d85228cbde1bba0134ce12c35123a450eb1864'
'vas_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Amon/vas/gn/v20210202/vas_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' 'c1ca578d2f1798fb38534e63799ed58386514df5816fec1d16d1ed6502c9b5f7'
'uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20150101-20391231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/day/uas/gn/v20210202/uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20150101-20391231.nc' 'SHA256' '5bbf632bc5edc22a016b181fe710fb081c94161d205abea523c4ed0f4fda65d2'
'psl_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Amon/psl/gn/v20210202/psl_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '55ccc198f202f0f825a2c2fb61651cf10ab0e71e4ae3ec568f8914750d6d7099'
'uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20900101-21001231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/day/uas/gn/v20210202/uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20900101-21001231.nc' 'SHA256' 'b5c31da6f91e4582040cccf8e0350d7d3110a13c7d4637dc03d2e3ac67f89ed6'
'uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/uo/gn/v20210202/uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' 'fbc97a127fc6473c2d6ba928cd57c15dee654244d05317045c28ad6d5f2cfaa9'
'thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/thetao/gn/v20210202/thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '23b8f3eedc0b318690d27fcd5816479d3e1fda8cb7c42850e9fe71781a0ee785'
'uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/uo/gn/v20210202/uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '90849a6aedddb7d800b39953a8b44874dc83bf1c465b85dbaedebcf0214fdc8f'
'sos_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/sos/gn/v20210202/sos_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '31e09e2eb72573a7baf159e840d6aab139fe41884478bce40cbbadc19a0a05bc'
'vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/vo/gn/v20210202/vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' '6b29d3476fcf6f23ebec5b4cf52802ed2f2b246e0185f98a3d273c8f72c80ee6'
'uas_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Amon/uas/gn/v20210202/uas_Amon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '47612bc1e4afb97b174c71dac645d8f0d32a1841afe44a328fd1224af7ca81d3'
'mlotst_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/mlotst/gn/v20210202/mlotst_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-210012.nc' 'SHA256' '06c83bfc50036b7b258689606ee76a49e5ecfa3453e016eada837d1b49513533'
'vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/vo/gn/v20210202/vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_201501-203412.nc' 'SHA256' '6db8497a0dffc937dd80fd382e1ad38d73fd4233cd60bcbf50f4efe7ec078428'
'vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/vo/gn/v20210202/vo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' '7e60fbe5808b8bde13a7fec54fb3eb6e1b6cfe27843a62d96854f088e10be93a'
'uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20400101-20641231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/day/uas/gn/v20210202/uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20400101-20641231.nc' 'SHA256' '388b28718dc92467e5309b191369522049bd68aff3c15c6e103b177e5fd2ddbd'
'uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/uo/gn/v20210202/uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_207501-209412.nc' 'SHA256' 'f80fa5561126fa09523a82a0eae5eaada47090f5b8da96680949973d16eddb5f'
'uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/uo/gn/v20210202/uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_203501-205412.nc' 'SHA256' 'f03db00a85ab8285ee2e70dfe8c943a7a99264df9d03587d066a256cadad6e9a'
'uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/uo/gn/v20210202/uo_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_205501-207412.nc' 'SHA256' '5e908d035c8dca96c2a561e8bac0497eae60b641bcf352ac67fff1373cb61de4'
'uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20650101-20891231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/day/uas/gn/v20210202/uas_day_CMCC-ESM2_ssp370_r1i1p1f1_gn_20650101-20891231.nc' 'SHA256' '2e0dc5810a9cf028ad9d077904c4fc39218b9a782921bfbbb77ac47879edd6d1'
'thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CMCC/CMCC-ESM2/ssp370/r1i1p1f1/Omon/thetao/gn/v20210202/thetao_Omon_CMCC-ESM2_ssp370_r1i1p1f1_gn_209501-210012.nc' 'SHA256' '52aeab461ea458746a2945d290f607bc2b0587acd5f7df95c9b96da93cfd9938'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 24 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
