#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/03 06:56:17
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Amon.psl.gn.v20191203|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Amon.uas.gn.v20191203|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Amon.vas.gn.v20191203|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.day.uas.gn.v20191203|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Omon.mlotst.gn.v20191203|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Omon.sos.gn.v20191203|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Omon.thetao.gn.v20191203|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Omon.uo.gn.v20191203|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp370.r3i1p1f1.Omon.vo.gn.v20191203|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'vas_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Amon/vas/gn/v20191203/vas_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' '86b4adbbe19cb8a7b1be1bd186542a336be36a8f1a87d9daf1fcc5767daaf540'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'SHA256' '26cfba8aa213e57fe7a9ccd310beca5691d6198c6381938c9b38775925dba952'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'SHA256' '9df4b78ee1c3d1f0b6793c3882bb41983432bdb649103c7a0160ed1f68d6e91a'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'SHA256' '9ed58d93e7477d86248c588db4de6e91b1e2cdab843359920343fcaa306ef4c8'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'SHA256' '42cad0c51bc608b401c9414bf83e6200ec2e0e5a20cc752515f0b81310be1216'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'SHA256' '63b92dea0da474e008ccedf67d772f2af9463cb61984e63194ae1c1045f40b35'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'SHA256' '760fb11483a70dd89742ccb768c24563a6f7aebdfd1a349700e4e90380b93bc5'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'SHA256' 'ad60078b7cab3f227ec4cb55cbe6908f03d43c1347f3483b879c4e83dec6c27f'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'SHA256' '382215dd2f3e0ae06f6dd9d4181eeec77755f3c6e050726568dba52708cada44'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'SHA256' '283bd4efaf9f65041ddcee4342cd7186c63410c4ca3e235ce261436df5ad84ae'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'SHA256' '65912e3ae581484ba52e4eb2534bc1249523566d490abfaf048f37982e892ded'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'SHA256' '3161237521e245f194ccdc332984f4c8a15e4aa87f3259abe79d8c11d0c3194c'
'mlotst_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/mlotst/gn/v20191203/mlotst_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' 'ffd50a85ad6c4a566a3a20da2a2aeddf8be6ebec94f2e4929836da33b9379caf'
'sos_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/sos/gn/v20191203/sos_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' '87132c2c6da48f2bbf52390f70cb7a3cb2a0f7b1dfca18bffbaffc84816e746a'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'SHA256' '41ece1666a622ad2c3f18c6c18629267e09c64662c26d9b5c099b5abd0af0640'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_206501-207412.nc' 'SHA256' 'b66d05143a418698912e9a445eff5204b9435654502b1251f518ed12c3704521'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'SHA256' 'a9e97eafda315a03d3c0ecda9c5e448242523017e63d4c12b66582829459457f'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_209501-210012.nc' 'SHA256' 'd69599c48cc81c8831af4d5df9d53683fe54f6b783fa219ed443fc5a1af1f726'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'SHA256' '1a967139188a6c223aac4bd5905858e3a0a1e97f978148ed752cfd3e45317a4d'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'SHA256' '9943fb08103f9b04c3875c7cc845914dd6d87342e181dbbd177ebcb1b413e737'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'SHA256' 'ec1c8303100e884c7c634f866179b974dd41be0e41c721efaffce2b4ea48e47a'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_207501-208412.nc' 'SHA256' '411ca800e586cfced83d30b7ed8ca9d2a9d77e4840b495114ce3da3180408a05'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_202501-203412.nc' 'SHA256' '0680296fa2bf3f31709e585fe213fb702e3931363697c5558df310db5d0db968'
'psl_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Amon/psl/gn/v20191203/psl_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' '87e5122977850a4ec8e19315c0be122b8d6d2b9eb41b4fc90b5793943ffefab6'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_205501-206412.nc' 'SHA256' '470fbd11a7af48a27dcea1bddc57e608f67c6a73f3dcc836598f5b434cf7edc6'
'uas_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Amon/uas/gn/v20191203/uas_Amon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-210012.nc' 'SHA256' '6d609cc356d96df23faf7d8c0b004952d9096bb1ddbb0095fa1aa689d35b44bf'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_204501-205412.nc' 'SHA256' 'dfdead4d9515738576b9563b5e00cc616be620631ecb5aef4fff79f8883eb6d6'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'SHA256' '203eb3096cca666e19a53b332cad699a632343e5cc681f3e1f559799d3b823b5'
'uas_day_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_20150101-20641231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/day/uas/gn/v20191203/uas_day_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_20150101-20641231.nc' 'SHA256' '16f26be79db83f51484d8d8681955172d02ed596c2fc10db301e30bcbec8cc8a'
'uas_day_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_20650101-21001231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/day/uas/gn/v20191203/uas_day_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_20650101-21001231.nc' 'SHA256' '32892b8d286e19ea671bee6345ed1bf5dd25a53046d5e6148d97b535dc144c54'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'SHA256' 'd296dde775c2fc52c4f23f28f4dd8847d77778aee6b3c1d2e3c18579f1f975a8'
'uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/uo/gn/v20191203/uo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_208501-209412.nc' 'SHA256' 'e9284499e5b6b248f4c22919a87b8aa1f9532f0a2a26681e0b7245dfafde1785'
'vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/vo/gn/v20191203/vo_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_201501-202412.nc' 'SHA256' '01cd9d1d4986a5cd8c07b3aeac6a675f2e115ecfb6e1ee583065a71be669c161'
'thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r3i1p1f1/Omon/thetao/gn/v20191203/thetao_Omon_ACCESS-ESM1-5_ssp370_r3i1p1f1_gn_203501-204412.nc' 'SHA256' '49a23b9677bd284121c545231519ced6dba7d6a06c7f15269689d133831b16ad'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 34 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
