#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/03/03 06:05:59
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Amon.psl.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Amon.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Amon.vas.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Omon.mlotst.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Omon.sos.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Omon.thetao.gn.v20190429|esgf-node.ornl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Omon.uo.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.Omon.vo.gn.v20190429|eagle.alcf.anl.gov&#x27;, &#x27;CMIP6.ScenarioMIP.CCCma.CanESM5.ssp370.r2i1p1f1.day.uas.gn.v20190429|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'mlotst_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/mlotst/gn/v20190429/mlotst_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'cbe0fa9fffcfaaaf38572f2c1a2fde905398fd53b0784357da92b4d8a2112884'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'SHA256' 'a6d281a89bd6b4f6ed038548753b43204f68a0722d712a46695bca4478bcbd87'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'SHA256' 'a7ccb1dadba74fdd9eee672a3cdc1e624471523725c580ee3aac0ef964c89b19'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'SHA256' 'bfd0c7d8b9e0d4ca4e23fd9e873d66123dd7889d3e32467f3027f1031ceb2ab6'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'SHA256' '7bb043895f3461cbf2c5839ecaec1ee73a096a02ae1f909e5c5d79bbe5891346'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_207101-208012.nc' 'SHA256' 'c5618307454f8186af6d4574d8eaeb5fb0f330f5f48ed6606ccf66b69ddd2de5'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'SHA256' '506316b1e9f27453332e9ddae6a93bd0c4439dbd785ad339c73462b35f259bd9'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'SHA256' '1e2ecac31d3bd7e1ff96a6557d6fef530e52c63d85dec3b7b425318805bfedb4'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'SHA256' 'f273b11e04db94153e9a63d68066b7e67c07a5f212587c5a3665c667633e26fd'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'SHA256' '5dc28c9ba42e14c94077621a70015ddf600d311b46d27b030adad1f39150b7eb'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'SHA256' 'c6cdf81e82a92ce728f89ae9bf993ea2be19531ab4f496e8ed4a150ee9e76cdd'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_203101-204012.nc' 'SHA256' 'd4e80800a06e38e9aa1e78563d75fea2cacc7c168eff98f954865df1c2a25597'
'vas_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Amon/vas/gn/v20190429/vas_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'b94d2aa4037488a6a518d76d9296b0438120a9076618315b984bd9f62bf9a1d9'
'sos_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/sos/gn/v20190429/sos_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'ad70d919ab64e24ec81fda841112c6b9cdfbbc27318d61477adb38cf3be8d27b'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'SHA256' '8aca36bb5c7a7360fcfa5e9c2f761b1fc5bb468cf3a58bf376159a47d59bf8e2'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'SHA256' '5d9c6015f4753d19f3f7ed7e7e4b991440a764de2416c1d6287ca3d8cad19844'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'SHA256' 'e2cd2c35d9425756f6b3d02bff12e804dc083cc33fca5ed75688b4348c7f7a2f'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'SHA256' '5db9f5634b93b279823c0d53a519182d1bedbce6908f1bf8f2afb660d4b31cb7'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'SHA256' 'c8f1d638dca65a4f008a1d43b386c5791fef60991229a324922f2d65a5ee232f'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'SHA256' 'd0b4b9d08bbc6ad5022e5979007df289e1cb9bbccb3c8f23baad20457c33efbe'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'SHA256' '4630b378953eee5e68c2cbe05495285dc1fbd36f98b24e1575f8e3ef7b000873'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_204101-205012.nc' 'SHA256' 'bc341d549c11e579d524e7f46b0fca3dce3b76ddf9881b6b3605fce9fb5029b1'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_205101-206012.nc' 'SHA256' 'a4ade902e1d3ea1432093140744652c6c4f539e09c7aeb1357f1eb84410e497c'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_208101-209012.nc' 'SHA256' 'd6442159f6649639e26350042b911321392448fafb017ad32168168a391fd35d'
'uas_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Amon/uas/gn/v20190429/uas_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' '7a3ac7646aab410f8fb48e6ef078794d17b3926d95d6a86881ae10279e6edaab'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'SHA256' '4e98f2e7386425965380d2bb7d44c920401760f2af2f7956f87b46df7a0d34de'
'psl_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Amon/psl/gn/v20190429/psl_Amon_CanESM5_ssp370_r2i1p1f1_gn_201501-210012.nc' 'SHA256' 'a5e787fd1a6de60b9d2dace98e4bf985bd43375dc498c82e6c9e16d2f7cb6ce7'
'uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/uo/gn/v20190429/uo_Omon_CanESM5_ssp370_r2i1p1f1_gn_206101-207012.nc' 'SHA256' 'ea6ca0291f2bf08141b1e6f0b42b9d94a5aa4de3d37c93cc62b9bfdd8d676eab'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'SHA256' 'a3f1b2eea780bdb4491aac025e8ca7e75d6dc04c9d0ed6433dfa409d35c560de'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_209101-210012.nc' 'SHA256' '0cba078956a51157a0f97067a96e90e627a5aea0c14216a29be932d589b1b15f'
'thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/thetao/gn/v20190429/thetao_Omon_CanESM5_ssp370_r2i1p1f1_gn_201501-202012.nc' 'SHA256' '8b0cb727d5208d8e0db999da2b9034e4abbc4dcd1f2c917613cf2ebb54a2abdc'
'uas_day_CanESM5_ssp370_r2i1p1f1_gn_20150101-21001231.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/day/uas/gn/v20190429/uas_day_CanESM5_ssp370_r2i1p1f1_gn_20150101-21001231.nc' 'SHA256' 'b385d750db64e20285a5771c98fa3d479439c605b61a93194be5c0c05fa5973f'
'vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/ScenarioMIP/CCCma/CanESM5/ssp370/r2i1p1f1/Omon/vo/gn/v20190429/vo_Omon_CanESM5_ssp370_r2i1p1f1_gn_202101-203012.nc' 'SHA256' '8d2a2cfe0cfdba291f93f929d9c18c56b80da7852a9038d1cb1dd7223ddc2772'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 33 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
